graylog:
  image: graylog2/allinone
  ports:
    - "9000:9000"
    - "12201:12201"
    - "12201:12201/udp"
  volumes:
    # Persist elasticsearch data on docker host
    - "/home/docker/graylog:/var/opt/graylog/data"
    # Linux volumes
    # - /graylog/data:/var/opt/graylog/data
    # - /graylog/logs:/var/log/graylog
